# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/redhat-gpte/scheduler
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

git:
  url: git@github.com:redhat-gpe/scheduler-config.git
  private_key: /.ssh/id_rsa
  redis_url: redis://agnostics-redis:6379/
  debug: \"true\"

initializePersistentVolumes: true

imagePullSecrets: []
nameOverride:
fullnameOverride:

redis:
  name: agnostics-redis
  port: 6379
  image:
    repository: redislabs/rejson
    pullPolicy: Always
    tag: "1.0.4"
  resources:
    limits:
      memory: 512Mi
  volume:
    size: 10Gi


service:
  type: ClusterIP
  port: 80

route:
  enabled: true
  annotations: {}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge


resources:
  limits:
    cpu: 500m
    memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
