---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agnostics-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: agnostics-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: agnostics-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: agnostics-redis
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.redis.port }}
            timeoutSeconds: 1
          ports:
            - containerPort: {{ .Values.redis.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/redis/data
              name: agnostics-redis-data

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: agnostics-redis-data
        persistentVolumeClaim:
          claimName: agnostics-redis
